server:
  port: 8080
  contextPath: /Igttest

spring:
  session:
    store-type: none
  #boot:
    #admin:
     #client:
        #service-url: http://localhost:8091/admin
     #url: http://localhost:8080
#todo: make sure to always enable security in production
security:
  basic:
    enabled: false
    
##management endpoints on a separate port
#management:
  #port: 8091
  #security:
    #enabled: false # management port is internal only. no need to secure it.